
-- BOOK
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1001, 2, 'Advanced Java EE Development for Rational Application Developer 7.5: Developers'' Guidebook');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1002, 3, 'Advanced Java EE Development for Rational Application Developer 7.5: Developers'' Guidebook Author: Robert McChesney Nov-2011');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1003, 5, 'Advanced Java EE Development for Rational Application Developer 7.5: Developers'' Guidebook 2nd , Seco edition by McChesney, Robert, Cole, Kameron, Raszka, Richard (2011) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1004, 3, 'Advanced Java EE Development with WildFly');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1005, 2, 'Advanced Jax-Ws Web Services');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1006, 5, 'Mike Meyers'' Guide to Supporting Windows 7 for CompTIA A+ Certification (Exams 701 & 702) (All-in-One)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1007, 1, 'Apache Maven 3 Cookbook (Quick Answers to Common Problems)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1008, 1, 'Apache Tomcat 7 - Guide d''administration du serveur Java EE 6 sous Windows et Linux');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1009, 2, 'Apache Tomcat 8 - Guide d''administration du serveur Java EE 7 sous Windows et Linux');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1010, 1, 'Apache TomEE Cookbook: Apache TomEE Administrator Cookbook');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1011, 4, 'Application Server 131 Success Secrets: 131 Most Asked Questions On Application Server - What You Need To Know');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1012, 2, 'Applied SOA Patterns on the Oracle Platform');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1013, 2, 'Architektur von Fuzzy-Informationssystemen (German Edition)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1014, 3, 'Java: A Beginner''s Guide, Sixth Edition');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1015, 5, 'jQuery: A Beginner''s Guide');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1016, 3, 'Java: A Beginner''s Tutorial, Updated for Java SE 8');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1017, 2, 'Beginning Android Application Development');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1018, 5, 'Beginning EJB 3 (Java EE 7 Edition)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1019, 1, 'Beginning EJB 3, Java EE, 7th 2nd (second) Edition by Wetherbee, Jonathan, Rathod, Chirag, Kodali, Raghu, Zadrozny published by Apress (2013)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1020, 1, 'Beginning EJB 3, Java EE, 7th ed.');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1021, 2, 'Beginning EJB 3, Java EE, 7th Edition');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1022, 1, 'Beginning EJB 3, Java EE, 7th Edition 2nd edition by Wetherbee, Jonathan, Kodali, Raghu, Rathod, Chirag, Zadrozny (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1023, 4, 'Beginning EJB 3, Java EE, 7th Edition by Wetherbee, Jonathan Published by Apress 2nd (second) edition (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1024, 2, 'Beginning EJB 3, Java EE, 7th Edition by Wetherbee, Jonathan, Rathod, Chirag, Kodali, Raghu, Zadrozny (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1025, 2, 'Beginning Ejb 3: Java Ee 7 Edition (Beginning Apress) by Jonathan Wetherbee (26-Apr-2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1026, 3, 'Beginning Ejb 3: Java Ee 7 Edition (Beginning Apress) by Wetherbee, Jonathan, Rathod, Chirag, Kodali, Raghu (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1027, 5, 'Beginning Java 7 (Expert''s Voice in Java)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1028, 3, 'Beginning Java EE 5: From Novice to Professional');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1029, 2, 'Beginning Java EE 6 Platform with GlassFish 3: From Novice to Professional (Expert''s Voice in Java Technology)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1030, 5, 'Beginning Java EE 6 with GlassFish 3 (Expert''s Voice in Java Technology)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1031, 1, 'Beginning Java EE 7');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1032, 1, 'Beginning Java EE 7 (Expert Voice in Java) 1st (first) by Goncalves, Antonio (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1033, 2, 'Beginning Java EE 7 (Expert Voice in Java) 1st edition by Goncalves, Antonio (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1034, 1, 'Beginning Java Ee 7 (Expert Voice in Java) by Goncalves, Antonio (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1035, 4, '[(Beginning Java EE 7 )] [Author: Antonio Goncalves] [Jul-2013]');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1036, 2, 'Beginning Java EE 7 1st (first) Edition by Goncalves, Antonio published by Apress (2013)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1037, 2, 'Beginning Java EE 7 by Goncalves, Antonio 1st (first) (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1038, 3, 'Beginning Java EE 7 by Goncalves, Antonio Published by Apress 1st (first) edition (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1039, 5, 'Beginning JSP, JSF and Tomcat: Java Web Development (Expert''s Voice in Java)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1040, 3, 'Beginning Spring');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1041, 2, 'Pro (IBM) WebSphere Application Server 7 Internals (Books for Professionals by Professionals)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1042, 5, 'Pro Spring 2.5 (Books for Professionals by Professionals)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1043, 1, 'Building Modular Cloud Apps with OSGi');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1044, 1, 'Business Service Management: What you Need to Know For IT Operations Management');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1045, 2, 'By Arun Gupta Java EE 7 Essentials (1st Edition)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1046, 1, 'By David R. Heffelfinger Java EE 7 with GlassFish 4 Application Server [Paperback]');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1047, 4, 'By Michal Cmil Java EE 7 Development with WildFly [Paperback]');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1048, 2, 'By Osama Oransa Java EE 7 Performance Tuning and Optimization [Paperback]');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1049, 2, 'C# 4.0 The Complete Reference');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1050, 3, 'CDI - Dependency Injection in Java EE 7 (German Edition)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1051, 5, 'NetBeans IDE Programmer Certified Expert Exam Guide (Exam 310-045) (Certification Press)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1052, 3, 'OCP Java SE 6 Programmer Practice Exams (Exam 310-065) (Certification Press)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1053, 2, 'RHCSA/RHCE Red Hat Linux Certification Study Guide (Exams EX200 & EX300), 6th Edition (Certification Press)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1054, 5, 'SCJA Sun Certified Java Associate Study Guide (Exam CX-310-019) (Certification Press)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1055, 1, 'Clojure High Performance Programming');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1056, 1, 'Cloud Computing: Methods and Practical Approaches (Computer Communications and Networks)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1057, 2, 'coffret Java EE 6 : développez et déployez une application sous Apache Tomcat 7');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1058, 1, 'ENTERprise Information Systems: International Conference, CENTERIS 2011, Vilamoura, Algarve, Portugal, October 5-7, 2011. Proceedings, Part III (Communications in Computer and Information Science)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1059, 4, 'Enterprise Java 2, J2EE 1.3 Complete');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1060, 2, 'The Computer Shelf.(nonfiction books)(Book review): An article from: Internet Bookwatch');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1061, 2, 'Continuous Enterprise Development in Java');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1062, 3, 'Java Cookbook');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1063, 5, 'Coupled Model Transformations for QoS Enabled Component-Based Software Design');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1064, 3, 'iText in Action: Creating and Manipulating PDF');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1065, 2, 'Developing Enterprise Applications with Spring: An End-to-End Approach');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1066, 5, 'Developing Enterprise Applications with Spring: An End-to-End Approach');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1067, 1, 'Developing RESTful Services with JAX-RS 2.0, WebSockets, and JSON');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1068, 1, 'Developing RESTful Web Services with Jersey 2.0');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1069, 2, 'ECUMICT 2014: Proceedings of the European Conference on the Use of Modern Information and Communication Technologies, Gent, March 2014 (Lecture Notes in Electrical Engineering)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1070, 1, 'EJB 3 Developer Guide: A Practical Guide for developers and architects to the Enterprise Java Beans Standard.');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1071, 4, 'EJB 3 in Action');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1072, 2, 'EJB 3 in Action');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1073, 2, 'Enterprise Application Development with Ext JS and Spring');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1074, 3, 'Enterprise JavaBeans 3.0 mit Eclipse und JBoss: Praxisbuch und Referenz');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1075, 5, 'Enterprise Software Architecture and Design: Entities, Services, and Resources');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1076, 3, 'Enterprise Web Development: Building HTML5 Applications: From Desktop to Mobile');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1077, 2, 'Organizations'' Environmental Performance Indicators: Measuring, Monitoring, and Management (Environmental Science and Engineering)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1078, 5, 'Java EE 7 Recipes: A Problem-Solution Approach (Expert''s Voice in Java)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1079, 1, 'Pro JPA 2 (Expert''s Voice in Java)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1080, 1, 'Pro JSF and HTML5: Building Rich Internet Components (Expert''s Voice in Java)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1081, 2, 'The Service-Oriented Media Enterprise: SOA, BPM, and Web Services in Professional Media Systems (Focal Press Media Technology Professional Series)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1082, 1, 'Gabler / MLP Berufs- und Karriere-Planer IT und e-business 2007/2008');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1083, 4, 'Gabler | MLP Berufs- und Karriere-Planer IT und e-business 2009 | 2010: Für Studenten und Hochschulabsolventen (German Edition)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1084, 2, 'Getting Started with Oracle WebLogic Server 12c: Developer''s Guide');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1085, 2, 'Getting Started with PhantomJS');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1086, 3, 'GIAC Secure Software Programmer - Java certification Exam Certification Exam Preparation Course in a Book for Passing the GSSP - Java Exam - The How To Pass on Your First Try Certification Study Guide');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1087, 5, 'GlassFish Security');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1088, 3, 'HCI in Business: First International Conference, HCIB 2014, Held as Part of HCI International 2014, Heraklion, Crete, Greece, June 22-27, 2014, Proceedings (Lecture Notes in Computer Science)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1089, 2, 'Modern Web Development with IBM WebSphere: Developing, Deploying, and Managing Mobile and Multi-Platform Apps (IBM Press)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1090, 5, 'Infinispan Data Grid Platform Definitive Guide');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1091, 1, 'Informationsintegration in dynamischen Unternehmensnetzwerken: Architektur, Methode und Anwendung (German Edition)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1092, 1, 'Instant JRebel');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1093, 2, 'Instant PrimeFaces Starter');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1094, 1, 'Integration Testing from the Trenches');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1095, 4, 'IntelliJ IDEA Essentials');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1096, 2, 'Introducing Java EE 7: A Look at What''s New by Juneau, Josh (2013) Paperback');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1097, 3, 'Introducing Java EE 7: A Look at What''s New');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1098, 5, 'Introducing Java EE 7: a Look at What''s New (Paperback) - Common');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1099, 1, 'Introducing Java EE 7: a Look at What''s New Author: Josh Juneau Jan-2014');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1100, 3, 'Introducing Java EE 7: A Look at What''s New 1st (first) Edition by Juneau, Josh published by Apress (2013)');

-- CD, rank
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1101, 2, 'Homenaje al Maestro Ernesto Lecuona');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1102, 3, 'Swingin Xmas Vol.2');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1103, 5, 'Swingin Xmas Vol.1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1104, 3, 'Weather Report 8:30');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1105, 2, 'Big Neighborhood');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1106, 5, 'Glenn Brown and Intergalactic Spiral');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1107, 1, '01');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1108, 1, 'Glenn Brown and Intergalactic Spiral (2)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1109, 2, 'Jazz Do It at 02:45 A.M.');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1110, 1, 'One-Day Session Vogue & Esoteric Rec');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1111, 4, 'Moni''s Jazz Quartett');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1112, 2, 'Esbjörn Svensson Trio');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1113, 2, 'Ryuichi Sakamoto 05');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1114, 3, 'The Ploctones 050');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1115, 5, '#1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1116, 3, 'Louis Prima 1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1117, 2, 'Ged Trio and 1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1118, 5, 'Emperors of Swing');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1119, 1, 'George Benson 20/20');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1120, 1, 'George Lewis n°1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1121, 2, 'Louis Prima and His New Orleans Gang');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1122, 1, 'Marc Atkinson');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1123, 4, 'The Compubodies');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1124, 2, 'Trime 1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1125, 2, 'ed Scantet Thigpen # 1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1126, 3, 'Ben Pollack');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1127, 5, '1 / 2 H Drama');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1128, 3, 'Billie Holiday 1933-1936');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1129, 2, 'Johnny Hodges 1937-1938');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1130, 5, 'Zoot Sims 1944-1950');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1131, 1, 'Fat Navarro 1946-1947');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1132, 1, 'Stan Getz 1952-1953');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1133, 2, '1 2 3');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1134, 1, 'Didier Lockwood 1 2 3 4');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1135, 4, 'Kick 1933-1942');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1136, 2, '1 2 to Bass');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1137, 2, 'The Bass By Stanley Clarke');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1138, 3, 'Hits Compilation');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1139, 5, 'Big Band Hits');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1140, 3, 'Classic Album & Skeets Mcdonald');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1141, 2, 'The #1 Guitar Album');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1142, 5, 'One Human, Too Human');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1143, 1, 'O''Clock Jump: 20 Original Big Band Hits');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1144, 1, 'Sampler Nagel Heyer');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1145, 2, 'Smooth Jazz Radio Hits by Loeb, Chuck (2009)');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1146, 1, 'Smooth Jazz Radio Hits by Loeb, Chuck (2009) Audio CD');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1147, 4, 'Swirl');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1148, 2, '1''st Sketches');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1149, 2, 'On The Sonny Side of the Street');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1150, 3, '1+1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1151, 5, '1+1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1152, 3, '1+1+1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1153, 2, '1+1+1+1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1154, 5, '1+1+1+1');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1155, 1, 'Jazz Ensemble With Remi Bolduc');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1156, 1, 'The $1,000,000 Collection');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1157, 2, '1,2,3,etc.');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1158, 1, '1-0');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1159, 4, 'Muhal Richard Abrams');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1160, 2, 'Barre Phillips');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1161, 2, 'A Chamada');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1162, 3, 'Baby, It''s Cold Outside');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1163, 5, 'Desafinado');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1164, 3, 'Introduction to Africa');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1165, 2, 'The Dum Dum Project');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1166, 5, '1.1=M');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1167, 1, 'Lars-Lindval-Tentet');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1168, 1, 'Half a Dozen');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1169, 2, 'A Fifth');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1170, 1, 'Ten');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1171, 4, '10');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1172, 2, 'Chris Daniels Kings');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1173, 2, 'Berroguetto');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1174, 3, 'Fop Form of Plasticity');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1175, 5, 'Ten');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1176, 3, 'Polish Jazz vol.14');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1177, 2, 'Diez Anos');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1178, 5, 'Des Anos Sem');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1179, 1, 'Anos Sem Vinicius');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1180, 1, 'Dix Ans De Succes');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1181, 2, 'Dix Ans Deja');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1182, 1, 'Ten By Two');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1183, 4, 'Ten compositions');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1184, 2, 'Duet');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1185, 2, 'Trio Derome Guilbeault Tanguay');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1186, 3, 'Counts of Jazz');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1187, 5, 'Counts of Jazz Fraud');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1188, 3, 'Coleccion');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1189, 2, 'Paco');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1190, 5, 'Fabulous recordings of the forties');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1191, 1, 'Grands 3');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1192, 1, 'Great Christmas Songs');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1193, 2, 'Great Years');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1194, 1, 'Chet Baker Quartet Pacific Jazz');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1195, 4, 'Jahre Interaction Jazz');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1196, 2, 'Melodies');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1197, 3, 'Minute Gentle Relaxation Meditation');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1198, 5, 'Mysteries');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1199, 1, 'Picture Disk');
INSERT INTO RATED_ITEM (id, rank, title) VALUES ( 1200, 3, 'Sides Of Ethel Ennis');
